//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExampleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACK_PACKING
    {
        public Nullable<long> LINE_ID { get; set; }
        public string ORDERNO { get; set; }
        public string POSNO { get; set; }
        public string LANGUAGE { get; set; }
        public string LABELTYPE { get; set; }
        public string FABRIC { get; set; }
        public string TAGNO { get; set; }
        public string MARKTEXT { get; set; }
        public string DIAMETER { get; set; }
        public string LENGTH { get; set; }
        public string BARCODE { get; set; }
        public Nullable<long> QTY { get; set; }
        public Nullable<long> QTYPACKED { get; set; }
        public Nullable<decimal> BOXWEIGHT_GL { get; set; }
        public Nullable<long> BOXHEIGHT { get; set; }
        public Nullable<long> BOXWIDTH { get; set; }
        public Nullable<long> BOXLENGTH { get; set; }
        public string STATUS { get; set; }
        public string CATEGORY { get; set; }
        public string DESCRIPTION { get; set; }
        public string UNIT { get; set; }
        public string CREATEDATE_GL { get; set; }
        public string BOXSIZE { get; set; }
        public string PARTTYPE { get; set; }
        public Nullable<decimal> BOXNO { get; set; }
        public Nullable<decimal> BOXWEIGHT { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public long ID { get; set; }
    }
}
