//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExampleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACK_WASHINGLABELS
    {
        public string ORDERNO { get; set; }
        public string POSNO { get; set; }
        public string LANGUAGE { get; set; }
        public string LABELTYPE { get; set; }
        public string DESCRIPTION { get; set; }
        public string FABRIC { get; set; }
        public string TAGNO { get; set; }
        public string MARKTEXT { get; set; }
        public string DIAMETER { get; set; }
        public string LENGTH { get; set; }
        public string BARCODE { get; set; }
        public string QTY { get; set; }
        public string STATUS { get; set; }
        public string FLOWMODEL { get; set; }
        public string UNITSYSTEM { get; set; }
        public long ID { get; set; }
    }
}
